baseURL = 'https://www.graphino.nl/'
languageCode = 'en-us'
title = 'Graphino'
theme = 'ananke'
enableRobotsTXT = true


[params]
  text_color = ""
  author = "Michael Cochez"
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-silver"
  recent_posts_number = 3
  disable_share=true
